name = "AutomotivePOMDPs"
uuid = "dca8afc0-c686-11e8-0934-712707da73aa"
repo = "https://github.com/sisl/AutomotivePOMDPs.jl"
version = "0.2.1"

[deps]
AutoUrban = "1385418a-9289-5a49-ab93-843b508de4cb"
AutoViz = "82aa6e0c-a491-5edf-8d4b-c16b98e4ea17"
AutomotiveDrivingModels = "99497e54-f3d6-53d3-a3a9-fa9315a7f1ba"
AutomotiveSensors = "9ec66b5e-c605-11e8-1454-ede748df6f96"
BeliefUpdaters = "8bb6e9a1-7d73-552c-a44a-e5dc5634aac4"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RLInterface = "3065fe53-3878-5aed-aae7-ab641be43734"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Records = "5984c134-fa48-5ed5-a57f-fc2f6936871f"
Reel = "71555da5-176e-5e73-a222-aebc6c6e4f2f"
Rsvg = "c4c386cf-5103-5370-be45-f3a111cca3b8"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Vec = "44eeaf0b-fee4-471f-9310-ed6585cb3142"

[extras]
POMDPTesting = "92e6a534-49c2-5324-9027-86e3c861ab81"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["POMDPTesting", "Test"]
